version: 2
jobs:
  check_version:
    docker:
      - image: alpine
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: check-version
          command: |
            apk add --no-cache make git openssh
            make check-version
          no_output_timeout: 5m
  test:
    docker:
      - image: python:3.10.0-alpine3.14
    steps:
      - checkout
      - run:
          name: smoke-test
          command: |
            wget -O /usr/local/bin/regctl https://github.com/regclient/regclient/releases/download/v${REGCTL_VER}/regctl-linux-amd64
            chmod a+x /usr/local/bin/regctl
            pip install -r requirements.txt
            echo "==== Starting REGBROOM ===="
            python -m regbroom -c .circleci/regbroom_config.yaml
          no_output_timeout: 5m
  release:
    docker:
      - image: alpine
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install packages
          command: apk add --no-cache docker-cli make
      - run:
          name: Docker image release
          command: |
            docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
            make release

workflows:
  version: 2
  checkver-test-release:
    jobs:
      - check_version:
          filters:
            branches:
              ignore: /^master$/
      - test:
          filters:
            # Tag triggers are ignored by default and must be enabled explicitly
            tags:
              only: /^\d\.\d\.\d$/
      - release:
          requires:
            - test
          filters:
            tags:
              only: /^\d\.\d\.\d$/
            branches:
              ignore: /.*/
